# Generated by Django 4.1.5 on 2023-01-20 04:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='raiting',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator, django.core.validators.MaxValueValidator]),
        ),
    ]
