# Generated by Django 4.1.5 on 2023-01-20 04:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_alter_blog_raiting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='raiting',
        ),
        migrations.CreateModel(
            name='BlogRaiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raiting', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator, django.core.validators.MaxValueValidator])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reytinqler', to='blog.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reytinqler', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
