# Generated by Django 4.1.5 on 2023-01-20 05:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_raiting_blograiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blograiting',
            name='raiting',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
